
version: build{build}
image: Visual Studio 2017
branches:
  only:
    - master
    - develop
environment:
  CODECAKEBUILDER_SECRET_KEY:
    secure: ks+QpMhDl8xJnpAmU4OHdfh11TE+fwNBj4PvMAKrPGsJnNjXcKgXtgAyJo77SJBi
build_script:
  - dotnet run --project CodeCakeBuilder -nointeraction
test: off
clone_folder: C:\CK-World\SimpleGitVersion\CSemVer-Net
install: 'ps: ./CodeCakeBuilder/InstallCredentialProvider.ps1'
