version: build{build}
image: Visual Studio 2022
branches:
  only:
  - master
  - develop
environment:
  CODECAKEBUILDER_SECRET_KEY:
    secure: 8VAzdXgUQaJyFoU3WLf2iPFV/8zPDm9qV4TfOpx8/rg=
test: false
clone_folder: C:\CKli-World\CK-Build\CSemVer-Net
on_finish:
- ps: Get-ChildItem -Recurse *.log -exclude LastRun.log | % { Push-AppveyorArtifact $_.FullName }
build_script:
- dotnet run --project CodeCakeBuilder -nointeraction
