
version: build{build}
image: Visual Studio 2017
branches:
  only:
    - master
    - develop
environment:
  CODECAKEBUILDER_SECRET_KEY:
    secure: 8VAzdXgUQaJyFoU3WLf2iPFV/8zPDm9qV4TfOpx8/rg=
build_script:
  - dotnet run --project CodeCakeBuilder -nointeraction
test: off
clone_folder: C:\CKli-World\SimpleGitVersion\CSemVer-Net
install:
  - ps: ./CodeCakeBuilder/InstallCredentialProvider.ps1
